### ISSUE TITLE
Bug when running on linux system

### ISSUE THREAD

**Issue by louieworth** [Sud0x67/city_brain_kit#1]
Hi, 

Thank you for your help. When I run this on my local system. In the previous step, it seemed fine. But when it reached the 981 step, it reported a bug. 
```
now training, traning step 981
start_time_epoch = 0
max_time_epoch = 3600
report_log_rate = 10
warning_stop_time_log = 100
Error: File ./data/roadnet_warm_up.txt not found in Core::GetInfoFromFile()
Traceback (most recent call last):
  File "./main.py", line 76, in <module>
  File ".1/CBEngine/envs/CBEngine.py", line 180, in reset
ValueError: Node id is not unique
```
where `main.py`'s 76 line is:` obs, info = env.reset()`. However, If I run my codes in the docker, there's no bug related to this problem.

**Comment by Sud0x67** [comment]
sorry for the inconvenience. Would you like to tell me whether you just run the
 demo or your own code? I will check it at tomarrow night.

**Comment by Sud0x67** [comment]
Sorry for the inconvenience, would you like to tell me wether you just run the demo or your own code. I will check it at tomorrow night.

**Comment by louieworth** [comment]
I am running in my codes.

**Comment by Sud0x67** [comment]
Hi, @louieworth, I wonder to know  if you ran it on windows or  ran it with VsCode? I test the code with the demo.py and there is no problem. It seems an error that happens because you are at a wrong work directory, which alway happens with VSCode cause of inpropriate config.PyCharm is recomended if you are not familiar with VScode.

**Comment by louieworth** [comment]
Thank you, I am using Pycharm. Oppps, It's a really hard task for me.
